//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18047
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoologico.InstitucionesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Institucions", Namespace="http://schemas.datacontract.org/2004/07/Proyecto.Dominio")]
    [System.SerializableAttribute()]
    public partial class Institucions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataException", Namespace="http://schemas.datacontract.org/2004/07/Proyecto.Dominio")]
    [System.SerializableAttribute()]
    public partial class DataException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataError {
            get {
                return this.DataErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DataErrorField, value) != true)) {
                    this.DataErrorField = value;
                    this.RaisePropertyChanged("DataError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstitucionesWS.IGestionarInstitucion")]
    public interface IGestionarInstitucion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarInstitucion/ObtenerInstitucionRUC", ReplyAction="http://tempuri.org/IGestionarInstitucion/ObtenerInstitucionRUCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Zoologico.InstitucionesWS.DataException), Action="http://tempuri.org/IGestionarInstitucion/ObtenerInstitucionRUCDataExceptionFault", Name="DataException", Namespace="http://schemas.datacontract.org/2004/07/Proyecto.Dominio")]
        Zoologico.InstitucionesWS.Institucions ObtenerInstitucionRUC(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarInstitucion/ObtenerInstitucionRazon", ReplyAction="http://tempuri.org/IGestionarInstitucion/ObtenerInstitucionRazonResponse")]
        Zoologico.InstitucionesWS.Institucions ObtenerInstitucionRazon(string razon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarInstitucion/ListaInstitucion", ReplyAction="http://tempuri.org/IGestionarInstitucion/ListaInstitucionResponse")]
        Zoologico.InstitucionesWS.Institucions[] ListaInstitucion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionarInstitucionChannel : Zoologico.InstitucionesWS.IGestionarInstitucion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionarInstitucionClient : System.ServiceModel.ClientBase<Zoologico.InstitucionesWS.IGestionarInstitucion>, Zoologico.InstitucionesWS.IGestionarInstitucion {
        
        public GestionarInstitucionClient() {
        }
        
        public GestionarInstitucionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionarInstitucionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionarInstitucionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionarInstitucionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zoologico.InstitucionesWS.Institucions ObtenerInstitucionRUC(string ruc) {
            return base.Channel.ObtenerInstitucionRUC(ruc);
        }
        
        public Zoologico.InstitucionesWS.Institucions ObtenerInstitucionRazon(string razon) {
            return base.Channel.ObtenerInstitucionRazon(razon);
        }
        
        public Zoologico.InstitucionesWS.Institucions[] ListaInstitucion() {
            return base.Channel.ListaInstitucion();
        }
    }
}
