//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoologico.InstitucionesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Institucions", Namespace="http://schemas.datacontract.org/2004/07/Proyecto.Dominio")]
    [System.SerializableAttribute()]
    public partial class Institucions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataException", Namespace="http://schemas.datacontract.org/2004/07/Proyecto.Dominio")]
    [System.SerializableAttribute()]
    public partial class DataException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataError {
            get {
                return this.DataErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.DataErrorField, value) != true)) {
                    this.DataErrorField = value;
                    this.RaisePropertyChanged("DataError");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InstitucionesWS.IGestionarSede")]
    public interface IGestionarSede {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarSede/ObtenerInstitucionRUC", ReplyAction="http://tempuri.org/IGestionarSede/ObtenerInstitucionRUCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Zoologico.InstitucionesWS.DataException), Action="http://tempuri.org/IGestionarSede/ObtenerInstitucionRUCDataExceptionFault", Name="DataException", Namespace="http://schemas.datacontract.org/2004/07/Proyecto.Dominio")]
        Zoologico.InstitucionesWS.Institucions ObtenerInstitucionRUC(string ruc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarSede/ObtenerInstitucionRazon", ReplyAction="http://tempuri.org/IGestionarSede/ObtenerInstitucionRazonResponse")]
        Zoologico.InstitucionesWS.Institucions ObtenerInstitucionRazon(string razon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionarSede/ListaInstitucion", ReplyAction="http://tempuri.org/IGestionarSede/ListaInstitucionResponse")]
        Zoologico.InstitucionesWS.Institucions[] ListaInstitucion();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionarSedeChannel : Zoologico.InstitucionesWS.IGestionarSede, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionarSedeClient : System.ServiceModel.ClientBase<Zoologico.InstitucionesWS.IGestionarSede>, Zoologico.InstitucionesWS.IGestionarSede {
        
        public GestionarSedeClient() {
        }
        
        public GestionarSedeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionarSedeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionarSedeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionarSedeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Zoologico.InstitucionesWS.Institucions ObtenerInstitucionRUC(string ruc) {
            return base.Channel.ObtenerInstitucionRUC(ruc);
        }
        
        public Zoologico.InstitucionesWS.Institucions ObtenerInstitucionRazon(string razon) {
            return base.Channel.ObtenerInstitucionRazon(razon);
        }
        
        public Zoologico.InstitucionesWS.Institucions[] ListaInstitucion() {
            return base.Channel.ListaInstitucion();
        }
    }
}
