// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package pe.edu.zoo.model;

import org.springframework.beans.factory.annotation.Configurable;
import pe.edu.zoo.model.PersonDataOnDemand;

privileged aspect PersonDataOnDemand_Roo_Configurable {
    
    declare @type: PersonDataOnDemand: @Configurable;
    
}
